# Generated by Django 3.2.9 on 2022-07-03 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcode', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=24)),
                ('batch_size', models.FloatField(default=1)),
                ('unit_of_measure', models.CharField(default='', max_length=16)),
                ('selling_price', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='cost',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='lead_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='minimum_order_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_of_measure',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='planning.product')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_forecast', to='planning.product')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_quantity', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_bom', to='planning.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_bom', to='planning.product')),
            ],
        ),
    ]
