# Generated by Django 3.2.9 on 2022-07-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_inventory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='forecast',
            new_name='quantity',
        ),
    ]
