# Generated by Django 3.2.9 on 2022-07-22 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0007_rename_forecast_forecast_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('minimum_order_quantity', models.IntegerField(default=1)),
                ('lead_time', models.IntegerField(default=1)),
                ('safety_stock_days', models.IntegerField(default=1)),
                ('current_inventory', models.FloatField(default=0)),
                ('forecast', models.FloatField(default=0)),
                ('safety_stock', models.FloatField(default=0)),
                ('proposal', models.FloatField(default=0)),
                ('closing_inventory', models.FloatField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_reordering', to='planning.material')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
