# Generated by Django 3.2.9 on 2022-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_reorderingplan_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorderingplan',
            name='name',
            field=models.CharField(default='', max_length=48),
        ),
    ]
