# Generated by Django 3.2.9 on 2022-07-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_alter_reorderingplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reorderingplan',
            name='closing_inventory',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='current_inventory',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='lead_time',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='material',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='minimum_order_quantity',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='safety_stock',
        ),
        migrations.RemoveField(
            model_name='reorderingplan',
            name='safety_stock_days',
        ),
        migrations.CreateModel(
            name='ReorderingPlanLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_order_quantity', models.IntegerField(default=1)),
                ('lead_time', models.IntegerField(default=1)),
                ('safety_stock_days', models.IntegerField(default=1)),
                ('current_inventory', models.FloatField(default=0)),
                ('forecast', models.FloatField(default=0)),
                ('safety_stock', models.FloatField(default=0)),
                ('proposal', models.FloatField(default=0)),
                ('closing_inventory', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_reordering', to='planning.material')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reordering_plan', to='planning.reorderingplan')),
            ],
        ),
    ]
