# Generated by Django 3.2.9 on 2022-07-26 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_rename_reorderingplanlines_reorderingplanline'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderingplan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
