# Generated by Django 3.2.2 on 2022-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_alter_material_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='reorderingplan',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
