# Generated by Django 3.2.2 on 2022-09-13 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0015_auto_20220731_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.FloatField(default=1)),
                ('safety_stock_days', models.IntegerField(default=1)),
                ('current_inventory', models.FloatField(default=0)),
                ('forecast', models.FloatField(default=0)),
                ('safety_stock', models.FloatField(default=0)),
                ('batches', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('closing_inventory', models.FloatField(default=0)),
                ('closing_inventory_days', models.IntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plan', to='planning.productionplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_production', to='planning.product')),
            ],
        ),
    ]
