# Generated by Django 3.2.2 on 2022-10-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_reorderingplan_production_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderingplanline',
            name='closing_inventory_days',
            field=models.IntegerField(default=1),
        ),
    ]
